spring.application.name=jjalgak
spring.config.import=optional:classpath:application-dev.properties
server.port = ${sv.port}

# [SLF4J]
logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.messaging=TRACE

# [DB] MongoDB
spring.data.mongodb.uri=mongodb://${mongodb.username}:${mongodb.password}@${mongodb.host}/${mongodb.dbname}

# [DB] MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${mysql.host}/${mysql.dbname}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${mysql.username}
spring.datasource.password=${mysql.password}

# [DB] Redis
spring.redis.host=${redis.host}
spring.redis.port=${redis.port}